version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rails_user
      POSTGRES_PASSWORD: rails_pass
      POSTGRES_DB: flatiron_mod3_development


volumes:
  db_data:
